#!/bin/bash

NAME="RASVAMT"
FLASKDIR=/home/rasvamt/rasvamt_portal/RASVAMT/
VENVDIR=/home/rasvamt/rasvamt_portal/
SOCKFILE=/home/rasvamt/rasvamt_portal/RASVAMT/sock
USER=rasvamt
GROUP=rasvamt_user
NUM_WORKERS=3

echo "Starting $NAME"

# activate the virtualenv
cd $VENVDIR
source bin/activate

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your unicorn
exec gunicorn main:app -b 127.0.0.1:5000 \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE
