#!/bin/bash
# Copyright (C) 2014  Cameron Poole & Joseph Dunne
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

NAME="RASVAMT"
FLASKDIR=/home/rasvamt/rasvamt_portal/RASVAMT/src
VENVDIR=/home/rasvamt/rasvamt_portal/
SOCKFILE=/home/rasvamt/rasvamt_portal/RASVAMT/sock
USER=rasvamt
GROUP=rasvamt_user
NUM_WORKERS=3

echo "Starting $NAME"

# activate the virtualenv
cd $VENVDIR
source bin/activate

export PYTHONPATH=$FLASKDIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

cd $FLASKDIR
# Start your unicorn
gunicorn main:app -b 127.0.0.1:5000 -D\
  --name $NAME \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --workers=$NUM_WORKERS \
  --log-level=debug
